In [1]:
import pandas as pd
import numpy as np


import sys
sys.path.insert(0, 'D:\DEV\iUtah\iUtahUtilities\src\GAMUTRawData')
#from odmdata import SessionFactory
from odmservices import ServiceManager
from datetime import datetime

ImportError: No module named GAMUTRawData.odmdata

In [ ]:
sm = ServiceManager()
sm._current_conn_dict= {'engine':'mssql', 'user':'webapplication' , 'password':'W3bAppl1c4t10n!', 'address':'iutahdbs.uwrl.usu.edu', 'db':'iUTAH_Logan_OD'}
   
ss = sm.get_series_service()


dvs = ss.get_all_values_by_site_id_date(1, datetime(1990,01,01))

db= [x.list_repr() for x in dvs]
s= ss.get_series_by_id(20)

db = db + [x.list_repr() for x in dvs]
df = pd.DataFrame(db, columns = ["ValueID"
      ,"DataValue"
      ,"ValueAccuracy"
      ,"LocalDateTime"
      ,"UTCOffset"
      ,"DateTimeUTC"
      ,"SiteID"
      ,"VariableID"
      ,"OffsetValue"
      ,"OffsetTypeID"
      ,"CensorCode"
      ,"QualifierID"
      ,"MethodID"
      ,"SourceID"
      ,"SampleID"
      ,"DerivedFromID"
      ,"QualityControlLevelID"])

In [2]:
df.set_index(["LocalDateTime"])

NameError: name 'df' is not defined

In [17]:

print len(df.index)
df=df.drop_duplicates()
print len(df.index)
df.set_index([ "ValueID", 'LocalDateTime', 'UTCOffset', 'DateTimeUTC'])

3804
1902

,,,,DataValue,ValueAccuracy,SiteID,VariableID,OffsetValue,OffsetTypeID,CensorCode,QualifierID,MethodID,SourceID,SampleID,DerivedFromID,QualityControlLevelID
ValueID,LocalDateTime,UTCOffset,DateTimeUTC,,,,,,,,,,,,,
888,1995-06-06 12:30:00,-5,1995-06-06 17:30:00,0.400,None,19,TN,NaN,NaN,nc,None,2,1,None,None,-9999
889,1995-06-06 12:30:00,-5,1995-06-06 17:30:00,0.008,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
890,1995-06-06 12:30:00,-5,1995-06-06 17:30:00,0.005,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
891,1995-06-06 12:30:00,-5,1995-06-06 17:30:00,0.400,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
892,1995-06-06 12:30:00,-5,1995-06-06 17:30:00,0.500,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
893,1995-07-11 12:20:00,-5,1995-07-11 17:20:00,0.370,None,19,TN,NaN,NaN,nc,None,2,1,None,None,-9999
894,1995-07-11 12:20:00,-5,1995-07-11 17:20:00,0.007,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
895,1995-07-11 12:20:00,-5,1995-07-11 17:20:00,0.500,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
896,1995-07-11 12:20:00,-5,1995-07-11 17:20:00,0.400,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
897,1995-07-11 12:40:00,-5,1995-07-11 17:40:00,0.320,None,19,TN,NaN,NaN,nc,None,2,1,None,None,-9999
898,1995-07-11 12:40:00,-5,1995-07-11 17:40:00,0.011,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
899,1995-07-11 12:40:00,-5,1995-07-11 17:40:00,0.007,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
900,1995-07-11 12:40:00,-5,1995-07-11 17:40:00,0.500,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
901,1995-07-11 12:40:00,-5,1995-07-11 17:40:00,0.900,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
902,1995-07-27 13:00:00,-5,1995-07-27 18:00:00,0.320,None,19,TN,NaN,NaN,nc,None,2,1,None,None,-9999
903,1995-07-27 13:00:00,-5,1995-07-27 18:00:00,0.008,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
904,1995-07-27 13:00:00,-5,1995-07-27 18:00:00,0.009,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
905,1995-07-27 13:00:00,-5,1995-07-27 18:00:00,0.600,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
906,1995-07-27 13:00:00,-5,1995-07-27 18:00:00,0.150,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
907,1995-07-27 13:30:00,-5,1995-07-27 18:30:00,0.390,None,19,TN,NaN,NaN,nc,None,2,1,None,None,-9999
908,1995-07-27 13:30:00,-5,1995-07-27 18:30:00,0.006,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
909,1995-07-27 13:30:00,-5,1995-07-27 18:30:00,0.007,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
910,1995-07-27 13:30:00,-5,1995-07-27 18:30:00,0.250,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
911,1995-07-27 13:30:00,-5,1995-07-27 18:30:00,0.500,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
912,1995-08-16 12:50:00,-5,1995-08-16 17:50:00,0.670,None,19,TN,NaN,NaN,nc,None,2,1,None,None,-9999
913,1995-08-16 12:50:00,-5,1995-08-16 17:50:00,0.007,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
914,1995-08-16 12:50:00,-5,1995-08-16 17:50:00,0.400,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
915,1995-08-16 12:50:00,-5,1995-08-16 17:50:00,0.600,None,19,TSS,NaN,NaN,nc,None,2,1,None,None,-9999
916,1995-08-16 13:15:00,-5,1995-08-16 18:15:00,0.300,None,19,TN,NaN,NaN,nc,None,2,1,None,None,-9999
917,1995-08-16 13:15:00,-5,1995-08-16 18:15:00,0.007,None,19,TP,NaN,NaN,nc,None,2,1,None,None,-9999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3742809,1997-05-28 10:15:00,-5,1997-05-28 15:15:00,4.910,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742810,1997-05-28 10:15:00,-5,1997-05-28 15:15:00,3.450,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742811,1997-05-29 12:20:00,-5,1997-05-29 17:20:00,5.160,None,19,Chla,2,1,nc,None,8,1,None,None,-9999
3742812,1997-06-03 10:15:00,-5,1997-06-03 15:15:00,7.660,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742813,1997-06-09 10:45:00,-5,1997-06-09 15:45:00,6.120,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742814,1997-06-09 10:45:00,-5,1997-06-09 15:45:00,6.360,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742815,1997-06-19 09:50:00,-5,1997-06-19 14:50:00,8.880,None,19,Chla,2,1,nc,None,8,1,None,None,-9999
3742816,1997-06-23 13:58:00,-5,1997-06-23 18:58:00,3.550,None,19,Chla,2,1,nc,None,8,1,None,None,-9999
3742817,1997-06-24 10:30:00,-5,1997-06-24 15:30:00,2.180,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742818,1997-06-24 10:30:00,-5,1997-06-24 15:30:00,3.000,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742819,1997-07-11 10:55:00,-5,1997-07-11 15:55:00,3.410,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742820,1997-07-11 10:55:00,-5,1997-07-11 15:55:00,2.030,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742821,1997-07-15 10:30:00,-5,1997-07-15 15:30:00,3.760,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742822,1997-07-21 11:01:00,-5,1997-07-21 16:01:00,2.960,None,19,Chla,2,1,nc,None,8,1,None,None,-9999
3742823,1997-07-30 10:20:00,-5,1997-07-30 15:20:00,1.780,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742824,1997-07-30 10:20:00,-5,1997-07-30 15:20:00,0.620,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742825,1997-08-12 10:15:00,-5,1997-08-12 15:15:00,3.250,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742826,1997-08-12 10:15:00,-5,1997-08-12 15:15:00,3.000,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742827,1997-08-19 10:10:00,-5,1997-08-19 15:10:00,4.380,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742828,1997-08-25 11:19:00,-5,1997-08-25 16:19:00,6.480,None,19,Chla,2,1,nc,None,8,1,None,None,-9999
3742829,1997-09-08 10:20:00,-5,1997-09-08 15:20:00,1.320,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742830,1997-09-08 10:20:00,-5,1997-09-08 15:20:00,4.500,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742831,1997-09-09 11:15:00,-5,1997-09-09 16:15:00,4.700,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742832,1997-09-23 11:20:00,-5,1997-09-23 16:20:00,4.760,None,19,Chla,2,1,nc,None,8,1,None,None,-9999
3742833,1997-10-07 10:10:00,-5,1997-10-07 15:10:00,3.060,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742834,1997-10-07 10:10:00,-5,1997-10-07 15:10:00,4.230,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742835,1997-10-07 10:30:00,-5,1997-10-07 15:30:00,3.630,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742836,1997-10-15 10:30:00,-5,1997-10-15 15:30:00,4.350,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742837,1997-10-15 10:30:00,-5,1997-10-15 15:30:00,4.550,None,19,Chla,NaN,NaN,nc,None,8,1,None,None,-9999
3742838,1997-10-20 11:25:00,-5,1997-10-20 16:25:00,5.140,None,19,Chla,2,1,nc,None,8,1,None,None,-9999

In [9]:
#print df
#print pivoted
#print pv
#print un

#print df
#df.columns = ["DataValue", "LocalDateTime", "CensorCode", "Month", "Year", "Season"]
#data = data.unstack(['observer', 'obstype'])
#data.columns = data.columns.droplevel(0)
df.set_index([ "ValueID", 'LocalDateTime', 'UTCOffset', 'DateTimeUTC']
             )
print""

In [21]:
#df=df.drop_duplicates()
#pv=df.pivot(index= "LocalDateTime", columns = "VariableID", values = "DataValue")
pv=pd.pivot_table(df,index= ["LocalDateTime", "UTCOffset","DateTimeUTC"], columns = "VariableID", values = "DataValue")

#df.unstack()

In [22]:
f=open(r'C:\Users\Stephanie\Desktop\csvsites\test.csv','w')
f.write("text\n\n\n")
pv.to_csv(f)
f.close()

In [ ]:
#append values to CSV
with open('my_csv.csv', 'a') as f:
    df.to_csv(f, header=False)

In [ ]:
un = df.unstack(level = ["LocalDateTime", "UTCDateTime"])